import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentAuth } from "@/lib/auth/current";

export default async function DashboardPage() {
  const auth = await getCurrentAuth();
  if (!auth) redirect("/?returnTo=/dashboard");
  const card = { border: "1px solid var(--ih-surface-border)", borderRadius: 16, padding: "1.25rem", background: "var(--ih-surface)" } as const;
  const link = { display: "inline-block", marginTop: ".5rem", padding: ".75rem 1rem", borderRadius: 10, background: "var(--ih-accent)", color: "var(--ih-accent-ink)", fontWeight: 700, textDecoration: "none" } as const;
  return <main style={{ padding: "3rem", fontFamily: "var(--ih-font-body)", background: "var(--ih-bg)", color: "var(--ih-text)", minHeight: "100vh" }}>
    <h1 style={{ fontFamily: "var(--ih-font-display)" }}>Welcome back, {auth.user.name ?? "there"}.</h1>
    <p style={{ color: "var(--ih-text-muted)", maxWidth: 760 }}>Your IntelliHire training workspace. Build the Career Digital Twin first, then research your target role with evidence before moving through the modules.</p>
    <div style={{ display: "grid", gap: "1.25rem", maxWidth: 900 }}>
      <section style={{ ...card, borderColor: "color-mix(in srgb, var(--ih-accent) 35%, var(--ih-surface-border))" }}><p style={{ margin: 0, font: "500 .72rem var(--ih-font-mono)", letterSpacing: ".12em", color: "var(--ih-accent)" }}>CAREER DIGITAL TWIN</p><h2 style={{ margin: ".4rem 0" }}>Evidence Skill Graph</h2><p style={{ color: "var(--ih-text-muted)", lineHeight: 1.6 }}>Map your resume against a target role and persist only the derived evidence graph.</p><Link href="/dashboard/career-twin" style={link}>Build Career Twin</Link></section>
      <section style={{ ...card, borderColor: "color-mix(in srgb, var(--ih-accent) 35%, var(--ih-surface-border))" }}><p style={{ margin: 0, font: "500 .72rem var(--ih-font-mono)", letterSpacing: ".12em", color: "var(--ih-accent)" }}>PERSONAL AI RESEARCH INTERN</p><h2 style={{ margin: ".4rem 0" }}>Evidence-backed research</h2><p style={{ color: "var(--ih-text-muted)", lineHeight: 1.6 }}>Ask role-relevant research questions using your Skill Graph as personalization context. External claims require retrieved sources.</p><Link href="/dashboard/research" style={link}>Open Research Intern</Link></section>
      <section style={card}><p style={{ margin: 0, font: "500 .72rem var(--ih-font-mono)", letterSpacing: ".12em", color: "var(--ih-accent)" }}>MODULE 01 / ATS</p><h2 style={{ margin: ".4rem 0" }}>AI Resume Screening</h2><p style={{ color: "var(--ih-text-muted)", lineHeight: 1.6 }}>Compare your resume with a target role and generate evidence-based ATS compatibility, strengths, gaps, and recommendations.</p><Link href="/dashboard/module-1" style={link}>Open Module 1</Link></section>
      <section style={card}><p style={{ margin: 0, font: "500 .72rem var(--ih-font-mono)", letterSpacing: ".12em", color: "var(--ih-accent)" }}>MODULE 02 / ADAPTIVE ASSESSMENT</p><h2 style={{ margin: ".4rem 0" }}>Adaptive AI Assessment</h2><p style={{ color: "var(--ih-text-muted)", lineHeight: 1.6 }}>Answer calibrated questions across aptitude, reasoning, verbal, domain, and coding sections.</p><Link href="/dashboard/module-2" style={link}>Open Module 2</Link></section>
      <section style={card}><p style={{ margin: 0, font: "500 .72rem var(--ih-font-mono)", letterSpacing: ".12em", color: "var(--ih-accent)" }}>MODULE 03 / TECHNICAL INTERVIEW</p><h2 style={{ margin: ".4rem 0" }}>AI Technical Interview</h2><p style={{ color: "var(--ih-text-muted)", lineHeight: 1.6 }}>Practice technical reasoning, DSA, system design, and project trade-offs with saved evaluation history.</p><Link href="/dashboard/module-3" style={link}>Open Module 3</Link></section>
      <section style={card}><p style={{ margin: 0, font: "500 .72rem var(--ih-font-mono)", letterSpacing: ".12em", color: "var(--ih-accent)" }}>MODULE 04 / HR INTERVIEW</p><h2 style={{ margin: ".4rem 0" }}>Real-Time HR Interview</h2><p style={{ color: "var(--ih-text-muted)", lineHeight: 1.6 }}>Practice behavioral, teamwork, ownership, and motivation questions with evidence-based coaching.</p><Link href="/dashboard/module-4" style={link}>Open Module 4</Link></section>
      <section style={card}><p style={{ margin: 0, font: "500 .72rem var(--ih-font-mono)", letterSpacing: ".12em", color: "var(--ih-accent)" }}>MODULE 05 / PERFORMANCE INSIGHTS</p><h2 style={{ margin: ".4rem 0" }}>Performance Insights</h2><p style={{ color: "var(--ih-text-muted)", lineHeight: 1.6 }}>Bring assessment and interview evidence into one readiness profile with gaps and recommendations.</p><Link href="/dashboard/module-5" style={link}>Open Module 5</Link></section>
    </div>
    <form action="/api/auth/logout" method="post" style={{ marginTop: "2rem" }}><button type="submit">Sign out</button></form>
  </main>;
}
